/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "FrameWinDLGSweeper.h"
#include "ADF4350_Messages.h"

extern unsigned long Register_Buf[12];

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0     (GUI_ID_USER + 0x00)
#define ID_BUTTON_0     (GUI_ID_USER + 0x01)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
    { FRAMEWIN_CreateIndirect,  "ADF4351 Sweep Generator",0,                      0,  0,  320,240,0,0},
    { TEXT_CreateIndirect,      "Xtal Freq",           GUI_ID_TEXT1,            181,24, 46, 16, 0,0},
    { TEXT_CreateIndirect,      "Mhz",               GUI_ID_TEXT2,            269,25, 24, 16, 0,0},
    { EDIT_CreateIndirect,       NULL,               GUI_ID_EDIT0,            233,18, 30, 22, 0,0},  //xtal
    { EDIT_CreateIndirect,       NULL,               GUI_ID_EDIT1,            81, 18, 60, 26, 0,0},  //Freq rf_out
    { BUTTON_CreateIndirect,    "RF_OUT",            GUI_ID_BUTTON0,          9,  18, 66, 26, 0,0},
    { BUTTON_CreateIndirect,    "START_Freq",         GUI_ID_BUTTON1,          9,  77, 66, 26, 0,0},
    { BUTTON_CreateIndirect,    "STOP Freq",          GUI_ID_BUTTON2,          9,  126,66, 26, 0,0},
    { BUTTON_CreateIndirect,    "Delta Freq",         GUI_ID_BUTTON3,          161,77, 66, 26, 0,0},
    { BUTTON_CreateIndirect,    "Ramp_Clk",          GUI_ID_BUTTON4,          161,127,66, 26, 0,0},
    { BUTTON_CreateIndirect,    "START Sweep",       GUI_ID_BUTTON5,          31, 179,91, 26, 0,0},
    { BUTTON_CreateIndirect,    "STOP Sweep",        GUI_ID_BUTTON6,          192,179,91, 26, 0,0},
    { EDIT_CreateIndirect,       NULL,               GUI_ID_EDIT2,            81, 77, 52, 26, 0,0},  //Start_freq
    { EDIT_CreateIndirect,       NULL,               GUI_ID_EDIT3,            81, 126,52, 26, 0,0},  //Stop_freq
    { EDIT_CreateIndirect,       NULL,               GUI_ID_EDIT4,            233,77, 52, 26, 0,0},  //Delta_freq
    { EDIT_CreateIndirect,       NULL,               GUI_ID_EDIT5,            233,126,52, 26, 0,0},  //Ramp_clk
    { TEXT_CreateIndirect,      "uS",                GUI_ID_TEXT6,            291,137,16, 16, 0,0},
    { TEXT_CreateIndirect,      "Khz",               GUI_ID_TEXT0,            147,29, 17, 15, 0,0},
    { TEXT_CreateIndirect,      "Mhz",               GUI_ID_TEXT3,            136,87, 19, 16, 0,0},
    { TEXT_CreateIndirect,      "Mhz",               GUI_ID_TEXT5,            135,135,20, 17, 0,0},
    { TEXT_CreateIndirect,      "Khz",               GUI_ID_TEXT4,            289,87, 23, 16, 0,0},
    { TEXT_CreateIndirect,      "min:100K",          GUI_ID_TEXT7,            233,106,50, 12, 0,0},
    { TEXT_CreateIndirect,      "min:100uS",         GUI_ID_TEXT8,            233,154,50, 12, 0,0}
}  ;



/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

// should be in SubdialogKey.h
extern int CreateSubdialog(void);

//		SynchroScope();

static unsigned char Key_SW_Flag;
unsigned char Register_Index;
unsigned char Key_Return_Flag;

/*********************************************************************
*
*       Dialog callback routine
*/
static void _cbDialog(WM_MESSAGE * pMsg) 
{
	int NCode, Id;
	WM_HWIN hWin = pMsg->hWin;
	//WM_HWIN hDlg;
	WM_HWIN	hEdit0_Item = WM_GetDialogItem(hWin, GUI_ID_EDIT0);
	WM_HWIN	hEdit1_Item = WM_GetDialogItem(hWin, GUI_ID_EDIT1);
	WM_HWIN	hEdit2_Item = WM_GetDialogItem(hWin, GUI_ID_EDIT2);
	WM_HWIN	hEdit3_Item = WM_GetDialogItem(hWin, GUI_ID_EDIT3);
	WM_HWIN	hEdit4_Item = WM_GetDialogItem(hWin, GUI_ID_EDIT4);
	WM_HWIN	hEdit5_Item = WM_GetDialogItem(hWin, GUI_ID_EDIT5);
	
	switch (pMsg->MsgId) {
	case WM_PAINT:
		//PaintDialog(pMsg);
		EDIT_SetDecMode(hEdit0_Item, GetRefClk(), 1, 100, 0, 0);
		EDIT_SetDecMode(hEdit1_Item, Register_Buf[6], 100, 4400000, 0, 0);
		EDIT_SetDecMode(hEdit2_Item, Register_Buf[7], 35, 4400, 0, 0);
		EDIT_SetDecMode(hEdit3_Item, Register_Buf[8], 35, 4400, 0, 0);
		EDIT_SetDecMode(hEdit4_Item, Register_Buf[9], 100, 50000, 0, 0);
		EDIT_SetDecMode(hEdit5_Item, Register_Buf[10], 10, 100000, 0, 0);
		break;
	case WM_INIT_DIALOG:
		//InitDialog(pMsg);
		break;
	case WM_KEY:
		switch (((WM_KEY_INFO*)(pMsg->Data.p))->Key) {
		case GUI_KEY_ESCAPE:
			GUI_EndDialog(hWin, 1);
			break;
		case GUI_KEY_ENTER:
			GUI_EndDialog(hWin, 0);
			break;
		}
		break;
	case WM_NOTIFY_PARENT:
		Id = WM_GetId(pMsg->hWinSrc); 
		NCode = pMsg->Data.v;  
		if (Key_Return_Flag) {
			Key_Return_Flag = 0;
			EDIT_SetValue(hEdit1_Item, Register_Buf[6]);
			EDIT_SetValue(hEdit2_Item, Register_Buf[7]);
			EDIT_SetValue(hEdit3_Item, Register_Buf[8]);
			EDIT_SetValue(hEdit4_Item, Register_Buf[9]);
			EDIT_SetValue(hEdit5_Item, Register_Buf[10]);
			Key_SW_Flag = 1;
			Register_Index = 0;
		}  
		switch (Id) {
		case GUI_ID_OK:
			if (NCode == WM_NOTIFICATION_RELEASED)
				GUI_EndDialog(hWin, 0);
			break;
		case GUI_ID_CANCEL:
			if (NCode == WM_NOTIFICATION_RELEASED)
				GUI_EndDialog(hWin, 0);
			break;
		case GUI_ID_BUTTON0:
			switch (NCode) {
			case WM_NOTIFICATION_RELEASED:
				OnButtonClicked_RF_OUT(pMsg);
				break;
			}
			break;
		case GUI_ID_BUTTON1:
			switch (NCode) {
			case WM_NOTIFICATION_RELEASED:
				OnButtonClicked_Start_F(pMsg);
				if (Key_SW_Flag == 0) {
					Key_SW_Flag = 2;
					Register_Index = 2;//Freq0
					CreateSubdialog();
				} else
					Key_SW_Flag = 0;													
				break;
			}
			break;
		case GUI_ID_BUTTON2:
			switch (NCode) {
			case WM_NOTIFICATION_RELEASED:
				OnButtonClicked_Stop_F(pMsg);
				break;
			}
			break;
		case GUI_ID_BUTTON3:
			switch (NCode) {
			case WM_NOTIFICATION_RELEASED:
				OnButtonClicked_Delta_F(pMsg);
				break;
			}
			break;
		case GUI_ID_BUTTON4:
			switch (NCode) {
			case WM_NOTIFICATION_RELEASED:
				OnButtonClicked_Ramp_Clk(pMsg);
				break;
			}
			break;
		case GUI_ID_BUTTON5:
			switch (NCode) {
			case WM_NOTIFICATION_RELEASED:
				OnButtonClicked_Start_SW(pMsg);
				break;
			}
			break;
		case GUI_ID_BUTTON6:
			switch (NCode) {
			case WM_NOTIFICATION_RELEASED:
				OnButtonClicked_Stop_SW(pMsg);
				break;
			}
			break;
		case GUI_ID_EDIT1:
			switch (NCode) {
			case WM_NOTIFICATION_RELEASED:
				OnEditClicked_RF_Out(pMsg);
				if (Key_SW_Flag == 0) {
					Key_SW_Flag = 1;
					Register_Index = 1;//Freq0
					CreateSubdialog();
					WM_SetFocus(0);
				} else
					Key_SW_Flag = 0;												
				break;
			}
			break;
		case GUI_ID_EDIT2:
			switch (NCode) {
			case WM_NOTIFICATION_RELEASED:
				OnEditClicked_Start_F(pMsg);
				if (Key_SW_Flag == 0) {
					Key_SW_Flag = 2;
					Register_Index = 2;//Freq0
					CreateSubdialog();
				} else
					Key_SW_Flag = 0;													
				break;
			}
			break;
		case GUI_ID_EDIT3:
			switch (NCode) {
			case WM_NOTIFICATION_RELEASED:
				OnEditClicked_Stop_F(pMsg);
				if (Key_SW_Flag == 0) {
					Key_SW_Flag = 3;
					Register_Index = 3;//Freq0
					CreateSubdialog();
				} else
					Key_SW_Flag = 0;													
				break;
			}
			break;
		case GUI_ID_EDIT4:
			switch (NCode) {
			case WM_NOTIFICATION_RELEASED:
				OnEditClicked_Delta_F(pMsg);
				if (Key_SW_Flag == 0) {
					Key_SW_Flag = 4;
					Register_Index = 4;//Freq0
					CreateSubdialog();
				} else
					Key_SW_Flag = 0;													
				break;
			}
			break;
		case GUI_ID_EDIT5:
			switch (NCode) {
			case WM_NOTIFICATION_RELEASED:
				OnEditClicked_Ramp_Clk(pMsg);
				if (Key_SW_Flag == 0) {
					Key_SW_Flag = 5;
					Register_Index = 5;   //Ramp_clk
					CreateSubdialog();
				} else
					Key_SW_Flag = 0;	
				break;
			}
			break;

		}
		break;
	default:
		WM_DefaultProc(pMsg);
	}
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateFramewin
*/
WM_HWIN CreateFramewin(void);
WM_HWIN CreateFramewin(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

void DisplayCurrentFrequency(WM_HWIN hWin, double frequency){
	WM_HWIN	hEdit1_Item = WM_GetDialogItem(hWin, GUI_ID_EDIT1);

	EDIT_SetValue(hEdit1_Item, (int)(frequency*1000));
	WM_InvalidateWindow(hEdit1_Item);
}
// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
