/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "DIALOG.h"
#include "GUI.h"
#include "FrameWinDLGSweeper.h"
#include "ADF4350_Messages.h"
#include "ADF4350_V1.h"
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>

//external name
#define CreateFramewin CreateSweeperDialog
#define GUI_MAKE_COLOR(c) (c)

WM_HWIN hDialogSweeper;
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0     (GUI_ID_USER + 0x00)
#define ID_BUTTON_0     (GUI_ID_USER + 0x01)


// USER START (Optionally insert additional defines)
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0    (GUI_ID_USER + 0x00)
#define ID_BUTTON_0    (GUI_ID_USER + 0x01)
#define ID_BUTTON_1    (GUI_ID_USER + 0x02)
#define ID_BUTTON_2    (GUI_ID_USER + 0x03)
#define ID_BUTTON_3    (GUI_ID_USER + 0x04)
#define ID_BUTTON_4    (GUI_ID_USER + 0x05)
#define ID_BUTTON_5    (GUI_ID_USER + 0x06)
#define ID_BUTTON_6    (GUI_ID_USER + 0x07)
#define ID_BUTTON_7    (GUI_ID_USER + 0x08)
#define ID_BUTTON_8    (GUI_ID_USER + 0x09)
#define ID_BUTTON_9    (GUI_ID_USER + 0x0A)
#define ID_BUTTON_10    (GUI_ID_USER + 0x0B)
#define ID_BUTTON_11    (GUI_ID_USER + 0x0C)
#define ID_BUTTON_12    (GUI_ID_USER + 0x0D)
#define ID_BUTTON_13    (GUI_ID_USER + 0x0E)
#define ID_EDIT_0    (GUI_ID_USER + 0x0F)
#define ID_EDIT_1    (GUI_ID_USER + 0x10)
#define ID_EDIT_2    (GUI_ID_USER + 0x11)
#define ID_EDIT_3    (GUI_ID_USER + 0x12)
#define ID_EDIT_4    (GUI_ID_USER + 0x13)
#define ID_EDIT_5    (GUI_ID_USER + 0x14)
#define ID_EDIT_6    (GUI_ID_USER + 0x15)
#define ID_EDIT_7    (GUI_ID_USER + 0x16)
#define ID_EDIT_8    (GUI_ID_USER + 0x17)
#define ID_BUTTON_14    (GUI_ID_USER + 0x18)
#define ID_BUTTON_15    (GUI_ID_USER + 0x19)
#define ID_BUTTON_16    (GUI_ID_USER + 0x1A)
#define ID_BUTTON_17    (GUI_ID_USER + 0x1B)
#define ID_EDIT_9    (GUI_ID_USER + 0x1C)
#define ID_EDIT_10    (GUI_ID_USER + 0x1D)
#define ID_EDIT_11    (GUI_ID_USER + 0x1E)
#define ID_EDIT_12    (GUI_ID_USER + 0x1F)
#define ID_TEXT_0    (GUI_ID_USER + 0x20)
#define ID_TEXT_1    (GUI_ID_USER + 0x21)
#define ID_TEXT_2    (GUI_ID_USER + 0x22)
#define ID_TEXT_3    (GUI_ID_USER + 0x23)
#define ID_PROGBAR_0    (GUI_ID_USER + 0x24)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
#define ID_BUTTON_M7 ID_BUTTON_0
#define ID_BUTTON_P7 ID_BUTTON_1
#define ID_BUTTON_M6 ID_BUTTON_3
#define ID_BUTTON_P6 ID_BUTTON_2
#define ID_BUTTON_M5 ID_BUTTON_5
#define ID_BUTTON_P5 ID_BUTTON_4
#define ID_BUTTON_M4 ID_BUTTON_7
#define ID_BUTTON_P4 ID_BUTTON_6
#define ID_BUTTON_M3 ID_BUTTON_10
#define ID_BUTTON_P3 ID_BUTTON_8
#define ID_BUTTON_M2 ID_BUTTON_12
#define ID_BUTTON_P2 ID_BUTTON_9
#define ID_BUTTON_M1 ID_BUTTON_13
#define ID_BUTTON_P1 ID_BUTTON_11

#define ID_EDIT_SWEEP_START ID_EDIT_0
#define ID_EDIT_SWEEP_STOP  ED_EDIT_1

#define ID_EDIT_DIGIT_7 ID_EDIT_2
#define ID_EDIT_DIGIT_6 ID_EDIT_3
#define ID_EDIT_DIGIT_5 ID_EDIT_4
#define ID_EDIT_DIGIT_4 ID_EDIT_5
#define ID_EDIT_DIGIT_3 ID_EDIT_6
#define ID_EDIT_DIGIT_2 ID_EDIT_7
#define ID_EDIT_DIGIT_1 ID_EDIT_8

// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "Framewin", ID_FRAMEWIN_0, 1, 0, 320, 210, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "-_7", ID_BUTTON_0, 20, 70, 20, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "+_7", ID_BUTTON_1, 20, 20, 20, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "+_6", ID_BUTTON_2, 71, 20, 20, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "-_6", ID_BUTTON_3, 71, 70, 20, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "+_5", ID_BUTTON_4, 106, 20, 20, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "-_5", ID_BUTTON_5, 106, 70, 20, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "+_4", ID_BUTTON_6, 142, 20, 20, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "-_4", ID_BUTTON_7, 142, 70, 20, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "+_3", ID_BUTTON_8, 196, 20, 20, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "+_2", ID_BUTTON_9, 230, 20, 20, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "-_3", ID_BUTTON_10, 196, 70, 20, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "+_1", ID_BUTTON_11, 264, 20, 20, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "-_2", ID_BUTTON_12, 230, 70, 20, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "-_1", ID_BUTTON_13, 264, 70, 20, 20, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "SW_SWEEP", ID_EDIT_0, 23, 105, 66, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "SW_STOP", ID_EDIT_1, 223, 105, 67, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit_7", ID_EDIT_2, 20, 45, 20, 20, 0, 0x1, 0 },
  { EDIT_CreateIndirect, "Edit_6", ID_EDIT_3, 71, 45, 20, 20, 0, 0x1, 0 },
  { EDIT_CreateIndirect, "Edit_5", ID_EDIT_4, 106, 45, 20, 20, 0, 0x1, 0 },
  { EDIT_CreateIndirect, "Edit_4", ID_EDIT_5, 142, 45, 20, 20, 0, 0x1, 0 },
  { EDIT_CreateIndirect, "Edit_3", ID_EDIT_6, 196, 45, 20, 20, 0, 0x1, 0 },
  { EDIT_CreateIndirect, "Edit_2", ID_EDIT_7, 230, 45, 19, 20, 0, 0x1, 0 },
  { EDIT_CreateIndirect, "Edit_1", ID_EDIT_8, 264, 45, 20, 20, 0, 0x1, 0 },
  { BUTTON_CreateIndirect, "SW_Start_F", ID_BUTTON_14, 13, 170, 60, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "SW_Stop_F", ID_BUTTON_15, 13, 145, 60, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "SW_Pas", ID_BUTTON_16, 177, 145, 60, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "SW_Vitesse", ID_BUTTON_17, 177, 170, 60, 20, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "Edit_Stop_F", ID_EDIT_9, 80, 145, 56, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit_Pas", ID_EDIT_10, 246, 145, 36, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit_Start_F", ID_EDIT_11, 80, 170, 56, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit_Vitesse", ID_EDIT_12, 246, 170, 36, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "kHz", ID_TEXT_0, 279, 145, 35, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "ms", ID_TEXT_1, 279, 170, 29, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "kHz", ID_TEXT_2, 143, 145, 26, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "kHz", ID_TEXT_3, 143, 170, 24, 20, 0, 0x0, 0 },
  { PROGBAR_CreateIndirect, "Progbar", ID_PROGBAR_0, 120, 105, 80, 20, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
bool bEditingField;
int savedFrequency;
typedef enum { frequencyCurrent, frequencyStart, frequencyStop, frequencyStep, frequencyTimeStep } frequencyDisplayType;
frequencyDisplayType displayShows;
WM_HWIN hWinStartFrequency;
WM_HWIN hWinStopFrequency;
WM_HWIN hWinStepFrequency;
WM_HWIN hWinTimeStep;
WM_HWIN hProgBar;

void DisplaySweepProgress(int percentSweep){
	PROGBAR_SetValue(hProgBar, percentSweep);
}

volatile int frequencyDigits[7];
typedef struct _digitItem {
	int idButtonMinus;
	int idButtonPlus;
	WM_HWIN hWinHandle;
} digitItem;

volatile digitItem digitItems[7];

int getFrequencyFromDisplay(bool bRestore);

void setDigit(int nDigit, char val){
	char szVal[2];
	szVal[1] = 0;
	szVal[0] = val;
	EDIT_SetText(digitItems[nDigit].hWinHandle, szVal);
}
void displayFrequencyDigits(){
	bool bZero = true;
	for (int i=6;i>=0;i--){
		if (frequencyDigits[i] == 0 && bZero) {
			setDigit(i, ' ');
		} else {
			if (frequencyDigits[i] != 0){
				bZero = false;
			}
			setDigit(i, '0' + frequencyDigits[i]);
		}
	}
}

void setMainFrequencyDisplay(int newFrequency, bool bSave)
{
	if (bSave) {
		savedFrequency = getFrequencyFromDisplay(false);
	}
	for (int i=0;i<7;i++){
		frequencyDigits[i] = newFrequency % 10;
		newFrequency /= 10;
	}
	displayFrequencyDigits();
}

void onDigitButtonAction(int NCode){
	for (int i=0;i<7;i++) {
		if (digitItems[i].idButtonMinus == NCode) {
			frequencyDigits[i] -= 1;
			if (frequencyDigits[i] < 0) {
				frequencyDigits[i] += 10;
			}
			frequencyDigits[i] %= 10;
			setDigit(i, '0' + frequencyDigits[i]);
		} else if (digitItems[i].idButtonPlus == NCode){
			frequencyDigits[i] += 1;
			frequencyDigits[i] %= 10;
			setDigit(i, '0' + frequencyDigits[i]);
		}
	}
	if (! bEditingField){
		sweepParameters.current = getFrequencyFromDisplay(false);
		DoRfOut();
	}
}
int getFrequencyFromDisplay(bool bRestore){
	int nResult = 0;
	for (int i=6;i>=0;i--){
		nResult += frequencyDigits[i];
		if (i != 0 ) {
			nResult *= 10;
		}
	}
	if (bRestore){
		setMainFrequencyDisplay(savedFrequency, false);
	}
	return nResult;
}
char buffer[8];
void setEditValue(int newValue,WM_HWIN hItem){
	char * szVal = (char*) itoa(newValue,buffer,10);
	EDIT_SetText(hItem, szVal);
}

void setStartFrequency(int newValue){
	setEditValue(newValue, hWinStartFrequency);
	sweepParameters.start = newValue;
}
void setStopFrequency(int newValue){
	setEditValue(newValue, hWinStopFrequency);
	sweepParameters.stop = newValue;
}
void setStepFrequency(int newValue){
	setEditValue(newValue, hWinStepFrequency);
	sweepParameters.step = newValue;
}
void setTimeStep(int newValue){
	setEditValue(newValue, hWinTimeStep);
	sweepParameters.timeStep = newValue;
}
void onStartSweep(){
	DoStartSweep();
}
void onStopSweep(){
	DoStopSweep();
}
void onStartFrequencyModify(){
	if (displayShows == frequencyCurrent) {
		displayShows = frequencyStart;
		setMainFrequencyDisplay(sweepParameters.start, true);
	} else if (displayShows == frequencyStart) {
		setStartFrequency(getFrequencyFromDisplay(true));
		displayShows = frequencyCurrent;
	} else {
		return;
	}
	bEditingField = !bEditingField;
}
void onStopFrequencyModify(){
	if (displayShows == frequencyCurrent) {
		displayShows = frequencyStop;
		setMainFrequencyDisplay(sweepParameters.stop, true);
	} else if (displayShows == frequencyStop) {
		setStopFrequency(getFrequencyFromDisplay(true));
		displayShows = frequencyCurrent;
	} else {
		return;
	}
	bEditingField = !bEditingField;
}
void onStepFrequencyModify(){
	if (displayShows == frequencyCurrent) {
		displayShows = frequencyStep;
		setMainFrequencyDisplay(sweepParameters.step, true);
	} else if (displayShows == frequencyStep) {
		setStepFrequency(getFrequencyFromDisplay(true));
		displayShows = frequencyCurrent;
	} else {
		return;
	}
	bEditingField = !bEditingField;
}
void onTimeStepModify(){
	if (displayShows == frequencyCurrent) {
		displayShows = frequencyTimeStep;
		setMainFrequencyDisplay(sweepParameters.timeStep, true);
	} else if (displayShows == frequencyTimeStep) {
		setTimeStep(getFrequencyFromDisplay(true));
		displayShows = frequencyCurrent;
	} else {
		return;
	}
	bEditingField = !bEditingField;
}
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Framewin'
    //
    hItem = pMsg->hWin;
    FRAMEWIN_SetTextColor(hItem, GUI_MAKE_COLOR(0x0000FFFF));
    FRAMEWIN_SetText(hItem, "ADF 4351 PLL     35 à 4400 MHz");
    FRAMEWIN_SetTitleHeight(hItem, 14);
    FRAMEWIN_SetTitleVis(hItem, 0);
    //
    // Initialization of '-_7'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetText(hItem, "-");
    BUTTON_SetFont(hItem, GUI_FONT_24B_ASCII);
    //
    // Initialization of '+_7'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetText(hItem, "+");
    BUTTON_SetFont(hItem, GUI_FONT_20B_ASCII);
    //
    // Initialization of '+_6'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
    BUTTON_SetText(hItem, "+");
    BUTTON_SetFont(hItem, GUI_FONT_20B_ASCII);
    //
    // Initialization of '-_6'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
    BUTTON_SetText(hItem, "-");
    BUTTON_SetFont(hItem, GUI_FONT_24B_ASCII);
    //
    // Initialization of '+_5'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
    BUTTON_SetText(hItem, "+");
    BUTTON_SetFont(hItem, GUI_FONT_20B_ASCII);
    //
    // Initialization of '-_5'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);
    BUTTON_SetText(hItem, "-");
    BUTTON_SetFont(hItem, GUI_FONT_24B_ASCII);
    //
    // Initialization of '+_4'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_6);
    BUTTON_SetText(hItem, "+");
    BUTTON_SetFont(hItem, GUI_FONT_20B_ASCII);
    //
    // Initialization of '-_4'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_7);
    BUTTON_SetText(hItem, "-");
    BUTTON_SetFont(hItem, GUI_FONT_24B_ASCII);
    //
    // Initialization of '+_3'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_8);
    BUTTON_SetText(hItem, "+");
    BUTTON_SetFont(hItem, GUI_FONT_20B_ASCII);
    //
    // Initialization of '+_2'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_9);
    BUTTON_SetText(hItem, "+");
    BUTTON_SetFont(hItem, GUI_FONT_20B_ASCII);
    //
    // Initialization of '-_3'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_10);
    BUTTON_SetText(hItem, "-");
    BUTTON_SetFont(hItem, GUI_FONT_24B_ASCII);
    //
    // Initialization of '+_1'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_11);
    BUTTON_SetText(hItem, "+");
    BUTTON_SetFont(hItem, GUI_FONT_20B_ASCII);
    //
    // Initialization of '-_2'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_12);
    BUTTON_SetText(hItem, "-");
    BUTTON_SetFont(hItem, GUI_FONT_24B_ASCII);
    //
    // Initialization of '-_1'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_13);
    BUTTON_SetText(hItem, "-");
    BUTTON_SetFont(hItem, GUI_FONT_24B_ASCII);
    //
    // Initialization of 'SW_SWEEP'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
    EDIT_SetText(hItem, "SWEEP");
    EDIT_SetTextColor(hItem, EDIT_CI_ENABLED, GUI_MAKE_COLOR(0x000000FF));
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    EDIT_SetFont(hItem, GUI_FONT_16B_ASCII);
    //
    // Initialization of 'SW_STOP'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);
    EDIT_SetText(hItem, "STOP");
    EDIT_SetTextColor(hItem, EDIT_CI_ENABLED, GUI_MAKE_COLOR(0x000000FF));
    EDIT_SetFont(hItem, GUI_FONT_16B_ASCII);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Edit_7'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_2);
    EDIT_SetText(hItem, "0");
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    EDIT_SetFont(hItem, GUI_FONT_13B_1);
    //
    // Initialization of 'Edit_6'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_3);
    EDIT_SetText(hItem, "0");
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    EDIT_SetFont(hItem, GUI_FONT_13B_1);
    //
    // Initialization of 'Edit_5'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_4);
    EDIT_SetText(hItem, "0");
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    EDIT_SetFont(hItem, GUI_FONT_13B_1);
    //
    // Initialization of 'Edit_4'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_5);
    EDIT_SetText(hItem, "0");
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    EDIT_SetFont(hItem, GUI_FONT_13B_1);
    //
    // Initialization of 'Edit_3'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_6);
    EDIT_SetText(hItem, "0");
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    EDIT_SetFont(hItem, GUI_FONT_13B_1);
    //
    // Initialization of 'Edit_2'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_7);
    EDIT_SetText(hItem, "0");
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    EDIT_SetFont(hItem, GUI_FONT_13B_1);
    //
    // Initialization of 'Edit_1'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_8);
    EDIT_SetText(hItem, "0");
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    EDIT_SetFont(hItem, GUI_FONT_13B_1);
    //
    // Initialization of 'SW_Start_F'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_14);
    BUTTON_SetText(hItem, "Start_F");
    //
    // Initialization of 'SW_Stop_F'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_15);
    BUTTON_SetText(hItem, "STOP_F");
    //
    // Initialization of 'SW_Pas'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_16);
    BUTTON_SetText(hItem, "Pas");
    //
    // Initialization of 'SW_Vitesse'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_17);
    BUTTON_SetText(hItem, "Vitesse");
    //
    // Initialization of 'Edit_Stop_F'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_9);
    EDIT_SetText(hItem, "0 000 000");
    EDIT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
    //
    // Initialization of 'Edit_Pas'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_10);
    EDIT_SetText(hItem, "0 000");
    EDIT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
    //
    // Initialization of 'Edit_Start_F'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_11);
    EDIT_SetText(hItem, "0 000 000");
    EDIT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
    //
    // Initialization of 'Edit_Vitesse'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_12);
    EDIT_SetText(hItem, "0000");
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'kHz'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetText(hItem, "kHz");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'ms'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'kHz'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    //
    // Initialization of 'kHz'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    //
    // Initialization of 'Progbar'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_0);
    PROGBAR_SetFont(hItem, GUI_FONT_16B_ASCII);
    // USER START (Optionally insert additional code for further widget initialization)
	digitItems[0].hWinHandle = WM_GetDialogItem(pMsg->hWin, ID_EDIT_DIGIT_1);
	digitItems[1].hWinHandle = WM_GetDialogItem(pMsg->hWin, ID_EDIT_DIGIT_2);
	digitItems[2].hWinHandle = WM_GetDialogItem(pMsg->hWin, ID_EDIT_DIGIT_3);
	digitItems[3].hWinHandle = WM_GetDialogItem(pMsg->hWin, ID_EDIT_DIGIT_4);
	digitItems[4].hWinHandle = WM_GetDialogItem(pMsg->hWin, ID_EDIT_DIGIT_5);
	digitItems[5].hWinHandle = WM_GetDialogItem(pMsg->hWin, ID_EDIT_DIGIT_6);
	digitItems[6].hWinHandle = WM_GetDialogItem(pMsg->hWin, ID_EDIT_DIGIT_7);
	digitItems[0].idButtonMinus = ID_BUTTON_M1;
	digitItems[0].idButtonPlus =  ID_BUTTON_P1;
	digitItems[1].idButtonMinus = ID_BUTTON_M2;
	digitItems[1].idButtonPlus =  ID_BUTTON_P2;
	digitItems[2].idButtonMinus = ID_BUTTON_M3;
	digitItems[2].idButtonPlus =  ID_BUTTON_P3;
	digitItems[3].idButtonMinus = ID_BUTTON_M4;
	digitItems[3].idButtonPlus =  ID_BUTTON_P4;
	digitItems[4].idButtonMinus = ID_BUTTON_M5;
	digitItems[4].idButtonPlus =  ID_BUTTON_P5;
	digitItems[5].idButtonMinus = ID_BUTTON_M6;
	digitItems[5].idButtonPlus =  ID_BUTTON_P6;
	digitItems[6].idButtonMinus = ID_BUTTON_M7;
	digitItems[6].idButtonPlus =  ID_BUTTON_P7;
	hWinStartFrequency = WM_GetDialogItem(pMsg->hWin, ID_EDIT_11);
	hWinStopFrequency = WM_GetDialogItem(pMsg->hWin, ID_EDIT_9);
	hWinStepFrequency = WM_GetDialogItem(pMsg->hWin, ID_EDIT_10);
	hWinTimeStep = WM_GetDialogItem(pMsg->hWin, ID_EDIT_12);
	hProgBar = WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_0);
	setMainFrequencyDisplay(sweepParameters.current, false);
	setStartFrequency(sweepParameters.start);
	setStopFrequency(sweepParameters.stop);
	setStepFrequency(sweepParameters.step);
	setTimeStep(sweepParameters.timeStep);
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by '-_7'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
	      onDigitButtonAction(Id);
	      onStopSweep();

        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by '+_7'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
	      onDigitButtonAction(Id);
	      onStopSweep();
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by '+_6'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
	      onDigitButtonAction(Id);
	      onStopSweep();
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by '-_6'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
	      onDigitButtonAction(Id);
	      onStopSweep();
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_4: // Notifications sent by '+_5'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
	      onDigitButtonAction(Id);
	      onStopSweep();
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_5: // Notifications sent by '-_5'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
	      onDigitButtonAction(Id);
	      onStopSweep();
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_6: // Notifications sent by '+_4'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
	      onDigitButtonAction(Id);
	      onStopSweep();
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_7: // Notifications sent by '-_4'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
	      onDigitButtonAction(Id);
	      onStopSweep();
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_8: // Notifications sent by '+_3'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
	      onDigitButtonAction(Id);
	      onStopSweep();
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_9: // Notifications sent by '+_2'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
	      onDigitButtonAction(Id);
	      onStopSweep();
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_10: // Notifications sent by '-_3'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
	      onDigitButtonAction(Id);
	      onStopSweep();
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_11: // Notifications sent by '+_1'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
	      onDigitButtonAction(Id);
	      onStopSweep();
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_12: // Notifications sent by '-_2'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
	      onDigitButtonAction(Id);
	      onStopSweep();
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_13: // Notifications sent by '-_1'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
	      onDigitButtonAction(Id);
	      onStopSweep();
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_0: // Notifications sent by 'SW_SWEEP'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
	      onStartSweep();
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_1: // Notifications sent by 'SW_STOP'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
	      onStopSweep();
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_2: // Notifications sent by 'Edit_7'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_3: // Notifications sent by 'Edit_6'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_4: // Notifications sent by 'Edit_5'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_5: // Notifications sent by 'Edit_4'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_6: // Notifications sent by 'Edit_3'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_7: // Notifications sent by 'Edit_2'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_8: // Notifications sent by 'Edit_1'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_14: // Notifications sent by 'SW_Start_F'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
	      onStartFrequencyModify();
	      onStopSweep();
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_15: // Notifications sent by 'SW_Stop_F'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
	      onStopFrequencyModify();
	      onStopSweep();
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_16: // Notifications sent by 'SW_Pas'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
	      onStepFrequencyModify();
	      onStopSweep();
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_17: // Notifications sent by 'SW_Vitesse'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
	      onTimeStepModify();
	      onStopSweep();
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_9: // Notifications sent by 'Edit_Stop_F'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_10: // Notifications sent by 'Edit_Pas'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_11: // Notifications sent by 'Edit_Start_F'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_12: // Notifications sent by 'Edit_Vitesse'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateFramewin
*/
WM_HWIN CreateFramewin(void);
WM_HWIN CreateFramewin(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
